// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDePbdcy5O2gReecYyJ6X3W_a29EnsVK0g',
    appId: '1:504000387893:web:98b7bc4ca078250b104a7c',
    messagingSenderId: '504000387893',
    projectId: 'care-me-plus',
    authDomain: 'care-me-plus.firebaseapp.com',
    storageBucket: 'care-me-plus.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWml-4i8IxNBA7ohlIzv3pUdAa5StI4_8',
    appId: '1:504000387893:android:38acb262c3c76915104a7c',
    messagingSenderId: '504000387893',
    projectId: 'care-me-plus',
    storageBucket: 'care-me-plus.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtTD26zy6MhiF-2VXTqCpU44gDrujY6Cw',
    appId: '1:504000387893:ios:59e65e1d16f2209b104a7c',
    messagingSenderId: '504000387893',
    projectId: 'care-me-plus',
    storageBucket: 'care-me-plus.firebasestorage.app',
    androidClientId: '504000387893-eufgu43uthprodgh4ced04h13pd8h3kr.apps.googleusercontent.com',
    iosClientId: '504000387893-tncldlb421usc0v3584jg8ua69qahhjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtTD26zy6MhiF-2VXTqCpU44gDrujY6Cw',
    appId: '1:504000387893:ios:59e65e1d16f2209b104a7c',
    messagingSenderId: '504000387893',
    projectId: 'care-me-plus',
    storageBucket: 'care-me-plus.firebasestorage.app',
    androidClientId: '504000387893-eufgu43uthprodgh4ced04h13pd8h3kr.apps.googleusercontent.com',
    iosClientId: '504000387893-tncldlb421usc0v3584jg8ua69qahhjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDePbdcy5O2gReecYyJ6X3W_a29EnsVK0g',
    appId: '1:504000387893:web:109e53f2e1b1a6f0104a7c',
    messagingSenderId: '504000387893',
    projectId: 'care-me-plus',
    authDomain: 'care-me-plus.firebaseapp.com',
    storageBucket: 'care-me-plus.firebasestorage.app',
  );
}
